[project]
name = "delegate-daemon"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.delegation-core]
path = "contracts/delegation-core.clar"
depends_on = []

[contracts.delegation-license]
path = "contracts/delegation-license.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
